perf: Additional fixes for 5.5+
In e5c4f3127521 ("perf: fix build for v5.5+") the recipe got a fix for
5.5 kernels. Testing shows that perf's build system also uses a file
from the scripts/ directory, so this must be added to the list of files
to perform a replace on.

This fixes warnings such as these, where the system python3 was being
used:

   File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
     _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
 ModuleNotFoundError: No module named '_sysconfigdata'

Signed-off-by: Joel Stanley <joel@jms.id.au>
Change-Id: I8d0011908c87d5fbcf1c3aefb362fe6beb64d22e